Game logic
TashfeenRao/tic-tac-toe pull request #4
Opened 2019-12-27 22:10 UTC by Qoosim

This PR contains of all the logics to play the tic-tac-toe game.
It also contains method to checkmate any invalid move attempt by either of the participants

2019-12-27 22:32 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

1. Please separate each class into a different file and put them inside the `lib` folder, ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/classes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)), ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

2. The `main.rb` should use the already defined classes in the `lib` folder to start the game and it should contain all the `puts` and `gets.chomp`, ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

3. The game can determine the winner successfully, but you have to make it stop the gameplay and displays a message that a player has won as soon as he has a combination, right now even if I win it would let me still play and switch turns until we finish all the empty spots and then it will say that I have won, fix that please.

4. Use `attr_readers/attr_writers` instead of `attr_accessors`. By using `attr_accessors` you allow writing that property from outside the class and that variable can be changed to anything, ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-12-28 17:00 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi team :wave: 

Nice implementing the changes requested by my colleague. However, there are some issues we need to fix.

- [ ] You should not have `puts/print` and `get.chomp` outside main.rb file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [ ] **Why did you configure a linter if you are going to ignore them?** Please remove all the `#rubocop:disable all` directives in your code so that your code would be properly linted!

_Kindly see below for more..._

**Please submit another code review request after attending to those issues.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-28 17:00 UTC, ebukaume commented on bin/main
>  #rubocop:disable all
Remove!

2019-12-28 17:00 UTC, ebukaume commented on lib/board.rb
> +
`puts` only allowed in `main.rb` file as stated above.

2019-12-28 17:00 UTC, ebukaume commented on lib/game_status.rb
> +#rubocop:disable all
Remove!

2019-12-28 17:00 UTC, ebukaume commented on lib/board.rb
> +#rubocop:disable all
Remove!

2019-12-28 17:00 UTC, ebukaume commented on lib/player.rb
> +#rubocop:disable all
Remove!

2019-12-28 17:00 UTC, ebukaume commented on lib/player.rb
> +  end
Return the message and use `puts` inside `main.rb` to display the message.

2019-12-28 17:00 UTC, ebukaume commented on lib/player.rb
> +  end
Same as above...

2019-12-28 19:32 UTC, imhta requested changes
# Changes required 🛑 

### Hello  @TashfeenRao @Qoosim  , 👋 You have done a great job in this project 👏 

* [ ] Why did you configure a linter if you are going to ignore them? In `.stickler.yml` don't exclude your project directory. Fix that
----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

2019-12-28 19:32 UTC, imhta commented on .rubocop.yml
> +  DisabledByDefault: true
You have excluded everything and disabled the cops
It is should not be like this.

2019-12-28 22:12 UTC, ebukaume requested changes
## Changes Required! :stop_sign: 

Hi team :wave: 

I really do not understand why you guys keep going back and forth on this. Please use the right configuration provided [here](https://github.com/microverseinc/linters-config/tree/master/ruby) by microverse. 

**Kindly submit another code review request affect makig that fix**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-12-28 22:12 UTC, ebukaume commented on .rubocop.yml
> +  Enabled: false
You are not supposed to modify anything in this file

2019-12-28 22:12 UTC, ebukaume commented on bin/main
>    end
`line 42` is always going to be flagged by rubocop. You just have to learn to write cleaner code. Please let's do the right thing.

2019-12-28 22:12 UTC, ebukaume commented on lib/player.rb
> +  end
Learn to keep your character length to a max of between 80 and 90. It will help you in the long run.

2019-12-30 15:39 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following issues need to be fixed before moving on ⬇️** 

_ Copy [this](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml) file and paste it into your `rubocop.yml` file exactly like it is **without any modifications**, you will then have about **5** linting errors, please fix then if you don't know how then you could also use `rubocop -a` command it would help you a bit with automatic fixes, but you need to fix anything else that doesn't get auto-fixed.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-12-30 20:23 UTC, Redvanisation approved these changes
# Project approved ✔️ 


### _Well done guys! it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

2019-12-30 20:26 UTC, merged